name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Free disk space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          tool-cache: true

      - name: Restore Unity Library Cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('Packages/manifest.json') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 6000.1.5f1
          projectPath: .
          targetPlatform: WebGL
          customImage: unityci/editor:ubuntu-6000.1.5f1-webgl-3.1.0

      - name: Save Unity Library Cache
        if: always() && steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('Packages/manifest.json') }}

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: WebGL
          path: build
